<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CustomconfigMap.php");

/**
 * CustomconfigDAO provides object-oriented access to the customConfig table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CustomconfigDAO extends Phreezable
{
	/** @var int */
	public $ConfigId;

	/** @var int */
	public $Salesorder;

	/** @var int */
	public $ConfigTarget;

	/** @var blob */
	public $ConfigContent;
        
        /** @var timestamp */
	public $TimeStamp;



	/**
	 * Returns the foreign object based on the value of ConfigTarget
	 * @return Networkequipment
	 */
	public function GetConfigTargetNetworkequipment()
	{
		return $this->_phreezer->GetManyToOne($this, "customConfig_ibfk_1");
	}


}
?>