<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ExecutionflagcodesMap.php");

/**
 * ExecutionflagcodesDAO provides object-oriented access to the executionFlagCodes table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ExecutionflagcodesDAO extends Phreezable
{
	/** @var int */
	public $Executionflag;

	/** @var string */
	public $Description;


	/**
	 * Returns a dataset of Remotecommands objects with matching Executionflag
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExecutionflagRemotecommandss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_execFlag", $criteria);
	}


}
?>