<?php
/** @package OdsDb::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("IP_valid_rangesMap.php");

/**
 * IP_valid_rangesDAO provides object-oriented access to the ip_ranges table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package OdsDb::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class IP_valid_rangesDAO extends Phreezable
{
	/** @var string */
	public $Start;

	/** @var string */
	public $End;

	/** @var int */
	public $Id;



}
?>