<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NetworkequipmentMap.php");

/**
 * NetworkequipmentDAO provides object-oriented access to the networkEquipment table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NetworkequipmentDAO extends Phreezable
{
	/** @var int */
	public $EquipId;

	/** @var string */
	public $EquipModel;

	/** @var int */
	public $Method;


	/**
	 * Returns the foreign object based on the value of Method
	 * @return Mediatype
	 */
	public function GetMethodMediatype()
	{
		return $this->_phreezer->GetManyToOne($this, "networkEquipment_ibfk_1");
	}


}
?>