<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NetworksMap.php");

/**
 * NetworksDAO provides object-oriented access to the networks table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NetworksDAO extends Phreezable
{
	/** @var int */
	public $Salesorder;

	/** @var string */
	public $Name;

	/** @var string */
	public $Ip;

	/** @var string */
	public $Mask;

	/** @var int */
	public $Vlanno;


	/**
	 * Returns the foreign object based on the value of Salesorder
	 * @return Orders
	 */
	public function GetSalesorderOrders()
	{
		return $this->_phreezer->GetManyToOne($this, "so");
	}


}
?>