<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("OrdersMap.php");

/**
 * OrdersDAO provides object-oriented access to the orders table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class OrdersDAO extends Phreezable
{
	/** @var int */
	public $Salesorder;

	/** @var string */
	public $Crmuid;

	/** @var string */
	public $Pgm;

	/** @var mediumtext */
	public $Ordertitle;

	/** @var string */
	public $Heacronym;

	/** @var string */
	public $Systemtype;

	/** @var int */
	public $Snapavail;

	/** @var date */
	public $Pstartdate;

	/** @var date */
	public $Penddate;

	/** @var date */
	public $Rstartdate;

	/** @var date */
	public $Renddate;

	/** @var date */
	public $Shippmentdate;

	/** @var string */
	public $Status;

	/** @var int */
	public $Polaroidexport;

	/** @var int */
	public $Userid;

	/** @var timestamp */
	public $Commiteddate;

	/** @var blob */
	public $Moveorder;

	/** @var blob */
	public $Oracleorder;

	/** @var string */
	public $Comments;


	/**
	 * Returns a dataset of Networks objects with matching Salesorder
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSalesorderNetworkss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "so", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Userid
	 * @return Users
	 */
	public function GetUseridUsers()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_userid_order");
	}


}
?>