<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProvisioningactionMap.php");

/**
 * ProvisioningactionDAO provides object-oriented access to the provisioningAction table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProvisioningactionDAO extends Phreezable
{
	/** @var int */
	public $Actionid;

	/** @var string */
	public $Salesorder;

	/** @var string */
	public $Codeapc;

	/** @var string */
	public $Rack;

	/** @var string */
	public $Shelf;

	/** @var string */
	public $Hostname;

	/** @var string */
	public $Timezone;

	/** @var string */
	public $Posixtz;

	/** @var string */
	public $Wintz;

	/** @var string */
	public $Dststartday;

	/** @var string */
	public $Dststopday;

	/** @var string */
	public $Dststarth;

	/** @var string */
	public $Dststoph;

	/** @var string */
	public $Os;

	/** @var string */
	public $Image;

	/** @var string */
	public $Boot;

	/** @var string */
	public $Ip;

	/** @var string */
	public $Netmask;

	/** @var string */
	public $Gateway;

	/** @var string */
	public $Iloip;

	/** @var string */
	public $Ilonm;

	/** @var string */
	public $Ilogw;

	/** @var string */
	public $Workgroup;

	/** @var string */
	public $Productkey;
        
        /** @var string */
	
	public $Creationdate;

}
?>