<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProvisioningnotificationsMap.php");

/**
 * ProvisioningnotificationsDAO provides object-oriented access to the provisioningNotifications table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProvisioningnotificationsDAO extends Phreezable
{
	/** @var string */
	public $Notifid;

	/** @var string */
	public $Hostname;

	/** @var string */
	public $Installationip;

	/** @var string */
	public $Configuredip;

	/** @var timestamp */
	public $Startdate;

	/** @var string */
	public $Status;

	/** @var float */
	public $Progress;

	/** @var string */
	public $Image;

	/** @var string */
	public $Firmware;

	/** @var string */
	public $Ram;

	/** @var string */
	public $Cpu;

	/** @var string */
	public $Diskscount;

	/** @var string */
	public $Netintcount;

	/** @var string */
	public $Model;

	/** @var string */
	public $Serial;

	/** @var string */
	public $Os;
        
        /** @var timestamp */
	public $Update;





}
?>