<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProvisioningscriptsMap.php");

/**
 * ProvisioningscriptsDAO provides object-oriented access to the provisioningScripts table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProvisioningscriptsDAO extends Phreezable
{
	/** @var int */
	public $Scriptid;

	/** @var int */
	public $Scripttarget;

	/** @var string */
	public $Scriptname;

	/** @var string */
	public $Scriptdescription;

	/** @var longblob */
	public $Scriptcontent;

	/** @var string */
	public $Interpreter;

	/** @var string */
	public $Version;


	/**
	 * Returns a dataset of Remotecommands objects with matching Scriptid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetScriptidRemotecommandss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "scriptID", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Scripttarget
	 * @return Mediatype
	 */
	public function GetScripttargetMediatype()
	{
		return $this->_phreezer->GetManyToOne($this, "scriptTarget");
	}


}
?>