<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProvisioningMap.php");

/**
 * ProvisioningDAO provides object-oriented access to the provisioning table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProvisioningDAO extends Phreezable
{
	/** @var int */
	public $Provisioningid;

	/** @var int */
	public $Salesorder;

	/** @var int */
	public $Rack;

	/** @var int */
	public $Shelf;

	/** @var int */
	public $Clientaddress;

	/** @var int */
	public $Arguments;

	/** @var int */
	public $Exesequence;

	/** @var int */
	public $Scriptid;

	/** @var int */
	public $Returncode;

	/** @var int */
	public $Returnstdout;

	/** @var int */
	public $Returnstderr;

	/** @var int */
	public $Executionflag;

	/** @var int */
	public $Logtime;

	/** @var int */
	public $Exectime;

	/** @var int */
	public $Scriptname;

	/** @var int */
	public $Scriptcontent;

	/** @var int */
	public $Remotecommandid;

	/** @var int */
	public $Interpreter;

	/** @var int */
	public $Version;



}
?>