<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SysprodracksmappingMap.php");

/**
 * SysprodracksmappingDAO provides object-oriented access to the sysprodRacksMapping table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SysprodracksmappingDAO extends Phreezable
{
	/** @var int */
	public $Rack;

	/** @var char */
	public $Shelf;

	/** @var char */
	public $Cycladesip;

	/** @var char */
	public $Cycladesport;

	/** @var char */
	public $Switchip;

	/** @var char */
	public $Switchport;

	/** @var char */
	public $Bootpip;

	/** @var int */
	public $Clientid;



}
?>