<?php
/** @package Spot::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SysprodracksMap.php");

/**
 * SysprodracksDAO provides object-oriented access to the sysprodracks table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Spot::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SysprodracksDAO extends Phreezable
{
	/** @var char */
	public $Idracks;

	/** @var char */
	public $Reponse;

	/** @var char */
	public $Machinetype;

	/** @var char */
	public $Ipaddress;

	/** @var timestamp */
	public $Timestamp;



}
?>